CREATE TABLE Companies (
    id VARCHAR(100) PRIMARY KEY DEFAULT NEWID(),
    name VARCHAR(255) UNIQUE NOT NULL,
    domain VARCHAR(255) UNIQUE NOT NULL,
	createdAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Tenants (
    id VARCHAR(100) PRIMARY KEY DEFAULT NEWID(),
    companyId VARCHAR(100) NOT NULL,
    dbName VARCHAR(255) UNIQUE NOT NULL,
	login NVARCHAR(255) UNIQUE NOT NULL,
	password NVARCHAR(255) NOT NULL,
    FOREIGN KEY (companyId) REFERENCES companies(id) ON DELETE CASCADE
);